/**
 * Mock CCTV surveillance data.
 * Kept separate so it can be replaced by Spring Boot REST responses
 * (and later WebSocket pushes) without touching UI code.
 */
import type { Camera, CameraDetection } from "@/utils/types";

const feed = (seed: string) => `https://picsum.photos/seed/${seed}/640/360`;
const snap = (seed: string) => `https://picsum.photos/seed/${seed}/480/320`;

export const mockCameras: Camera[] = [
  {
    id: "CAM-01",
    name: "Camera 01",
    place: "North Forest Entrance",
    zone: "Zone A",
    status: "Online",
    streamUrl: feed("cctv-north-entrance"),
    snapshotUrl: snap("cctv-north-entrance"),
    coordinates: { lat: 12.9412, lng: 77.5601 },
    lastDetectionTime: "10:42 AM",
  },
  {
    id: "CAM-02",
    name: "Camera 02",
    place: "Kaveri Waterhole",
    zone: "Zone A",
    status: "Online",
    streamUrl: feed("cctv-waterhole"),
    snapshotUrl: snap("cctv-waterhole"),
    coordinates: { lat: 12.9388, lng: 77.5399 },
    lastDetectionTime: "10:15 AM",
  },
  {
    id: "CAM-03",
    name: "Camera 03",
    place: "Hosur Corridor Trail",
    zone: "Zone B",
    status: "Online",
    streamUrl: feed("cctv-corridor"),
    snapshotUrl: snap("cctv-corridor"),
    coordinates: { lat: 12.9055, lng: 77.5122 },
    lastDetectionTime: "10:45 AM",
  },
  {
    id: "CAM-04",
    name: "Camera 04",
    place: "Fence Line 7",
    zone: "Zone C",
    status: "Offline",
    streamUrl: feed("cctv-fence"),
    snapshotUrl: snap("cctv-fence"),
    coordinates: { lat: 12.9309, lng: 77.5251 },
    lastDetectionTime: "02:12 AM",
  },
  {
    id: "CAM-05",
    name: "Camera 05",
    place: "Rocky Ridge Pass",
    zone: "Zone D",
    status: "Online",
    streamUrl: feed("cctv-ridge"),
    snapshotUrl: snap("cctv-ridge"),
    coordinates: { lat: 12.8975, lng: 77.5678 },
    lastDetectionTime: "09:30 AM",
  },
  {
    id: "CAM-06",
    name: "Camera 06",
    place: "Honey Rock Check Post",
    zone: "Zone E",
    status: "Offline",
    streamUrl: feed("cctv-honeyrock"),
    snapshotUrl: snap("cctv-honeyrock"),
    coordinates: { lat: 12.9502, lng: 77.4988 },
    lastDetectionTime: "11:05 PM",
  },
];

const today = new Date().toISOString().slice(0, 10);

export const mockCameraDetections: CameraDetection[] = [
  {
    id: "CDT-5012",
    cameraId: "CAM-03",
    cameraName: "Camera 03",
    species: "Tiger",
    confidence: 96,
    zone: "Zone B",
    location: "Hosur Corridor Trail, Zone B",
    coordinates: { lat: 12.9055, lng: 77.5122 },
    date: today,
    time: "10:45 AM",
    priority: "High",
    status: "New",
    snapshotUrl: snap("cctv-tiger"),
  },
  {
    id: "CDT-5011",
    cameraId: "CAM-01",
    cameraName: "Camera 01",
    species: "Human Footprint",
    confidence: 93,
    zone: "Zone A",
    location: "North Forest Entrance, Zone A",
    coordinates: { lat: 12.9412, lng: 77.5601 },
    date: today,
    time: "10:42 AM",
    priority: "High",
    status: "New",
    snapshotUrl: snap("cctv-human"),
  },
  {
    id: "CDT-5010",
    cameraId: "CAM-02",
    cameraName: "Camera 02",
    species: "Elephant",
    confidence: 89,
    zone: "Zone A",
    location: "Kaveri Waterhole, Zone A",
    coordinates: { lat: 12.9388, lng: 77.5399 },
    date: today,
    time: "10:15 AM",
    priority: "Medium",
    status: "New",
    snapshotUrl: snap("cctv-elephant"),
  },
  {
    id: "CDT-5009",
    cameraId: "CAM-05",
    cameraName: "Camera 05",
    species: "Leopard",
    confidence: 84,
    zone: "Zone D",
    location: "Rocky Ridge Pass, Zone D",
    coordinates: { lat: 12.8975, lng: 77.5678 },
    date: today,
    time: "09:30 AM",
    priority: "Medium",
    status: "Acknowledged",
    snapshotUrl: snap("cctv-leopard"),
  },
  {
    id: "CDT-5008",
    cameraId: "CAM-04",
    cameraName: "Camera 04",
    species: "Human Footprint",
    confidence: 87,
    zone: "Zone C",
    location: "Fence Line 7, Zone C",
    coordinates: { lat: 12.9309, lng: 77.5251 },
    date: "2026-08-02",
    time: "02:12 AM",
    priority: "High",
    status: "Acknowledged",
    snapshotUrl: snap("cctv-human2"),
  },
  {
    id: "CDT-5007",
    cameraId: "CAM-02",
    cameraName: "Camera 02",
    species: "Deer",
    confidence: 91,
    zone: "Zone A",
    location: "Kaveri Waterhole, Zone A",
    coordinates: { lat: 12.9388, lng: 77.5399 },
    date: "2026-08-02",
    time: "05:30 PM",
    priority: "Low",
    status: "Acknowledged",
    snapshotUrl: snap("cctv-deer"),
  },
];
