import type { AlertItem, Detection, MapMarker, Species } from "@/utils/types";

export const FOREST_CENTER: [number, number] = [12.9231, 77.5342];

export const SPECIES_LIST: Species[] = [
  "Tiger",
  "Elephant",
  "Leopard",
  "Bear",
  "Deer",
  "Human Footprint",
];

export const speciesEmoji: Record<Species, string> = {
  Tiger: "🐅",
  Elephant: "🐘",
  Leopard: "🐆",
  Bear: "🐻",
  Deer: "🦌",
  "Human Footprint": "🥾",
};

const img = (seed: string) =>
  `https://picsum.photos/seed/${seed}/160/160`;

export const mockDetections: Detection[] = [
  {
    id: "DET-1041",
    species: "Tiger",
    confidence: 96,
    zone: "Zone C",
    location: "Bandipur Range, Zone C",
    coordinates: { lat: 12.9231, lng: 77.5342 },
    date: "2026-08-03",
    time: "10:42 AM",
    source: "Footprint Upload",
    officerName: "Ranger Ravi",
    imageUrl: img("tiger-print"),
  },
  {
    id: "DET-1040",
    species: "Human Footprint",
    confidence: 91,
    zone: "Zone A",
    location: "Kaveri Belt, Zone A",
    coordinates: { lat: 12.9412, lng: 77.5601 },
    date: "2026-08-03",
    time: "08:15 AM",
    source: "Footprint Upload",
    officerName: "Ranger Ravi",
    imageUrl: img("human-print"),
  },
  {
    id: "DET-1039",
    species: "Elephant",
    confidence: 88,
    zone: "Zone B",
    location: "Hosur Corridor, Zone B",
    coordinates: { lat: 12.9055, lng: 77.5122 },
    date: "2026-08-02",
    time: "06:55 PM",
    source: "Footprint Upload",
    officerName: "Ranger Ravi",
    imageUrl: img("eleph-print"),
  },
  {
    id: "DET-1038",
    species: "Leopard",
    confidence: 84,
    zone: "Zone D",
    location: "Rocky Ridge, Zone D",
    coordinates: { lat: 12.8975, lng: 77.5678 },
    date: "2026-08-02",
    time: "04:20 AM",
    source: "Footprint Upload",
    officerName: "Ranger Ravi",
    imageUrl: img("leopard-print"),
  },
  {
    id: "DET-1037",
    species: "Bear",
    confidence: 79,
    zone: "Zone E",
    location: "Honey Rock, Zone E",
    coordinates: { lat: 12.9502, lng: 77.4988 },
    date: "2026-08-01",
    time: "11:05 PM",
    source: "Footprint Upload",
    officerName: "Ranger Ravi",
    imageUrl: img("bear-print"),
  },
  {
    id: "DET-1036",
    species: "Deer",
    confidence: 93,
    zone: "Zone B",
    location: "Grassland Patch, Zone B",
    coordinates: { lat: 12.9128, lng: 77.5455 },
    date: "2026-08-01",
    time: "05:30 PM",
    source: "Footprint Upload",
    officerName: "Ranger Ravi",
    imageUrl: img("deer-print"),
  },
  {
    id: "DET-1035",
    species: "Human Footprint",
    confidence: 87,
    zone: "Zone C",
    location: "Fence Line 7, Zone C",
    coordinates: { lat: 12.9309, lng: 77.5251 },
    date: "2026-07-31",
    time: "02:12 AM",
    source: "Footprint Upload",
    officerName: "Ranger Ravi",
    imageUrl: img("human2-print"),
  },
  {
    id: "DET-1034",
    species: "Tiger",
    confidence: 90,
    zone: "Zone A",
    location: "Waterhole 3, Zone A",
    coordinates: { lat: 12.9388, lng: 77.5399 },
    date: "2026-07-30",
    time: "09:47 PM",
    source: "Footprint Upload",
    officerName: "Ranger Ravi",
    imageUrl: img("tiger2-print"),
  },
];

export const mockAlerts: AlertItem[] = [
  {
    id: "ALT-321",
    title: "Human movement detected near fence line",
    kind: "Human",
    species: "Human Footprint",
    priority: "High",
    status: "New",
    source: "Footprint Upload",
    location: "Kaveri Belt, Zone A",
    date: "2026-08-03",
    time: "08:15 AM",
  },
  {
    id: "ALT-320",
    title: "Tiger footprint detected",
    kind: "Animal",
    species: "Tiger",
    priority: "High",
    status: "New",
    source: "Footprint Upload",
    location: "Bandipur Range, Zone C",
    date: "2026-08-03",
    time: "10:42 AM",
  },
  {
    id: "ALT-319",
    title: "Elephant spotted near village boundary",
    kind: "Animal",
    species: "Elephant",
    priority: "High",
    status: "Acknowledged",
    source: "Footprint Upload",
    location: "Hosur Corridor, Zone B",
    date: "2026-08-02",
    time: "06:55 PM",
  },
  {
    id: "ALT-318",
    title: "Bear footprint recorded",
    kind: "Animal",
    species: "Bear",
    priority: "Medium",
    status: "Acknowledged",
    source: "Footprint Upload",
    location: "Honey Rock, Zone E",
    date: "2026-08-01",
    time: "11:05 PM",
  },
  {
    id: "ALT-317",
    title: "Leopard movement on patrol trail",
    kind: "Animal",
    species: "Leopard",
    priority: "Medium",
    status: "New",
    source: "Footprint Upload",
    location: "Rocky Ridge, Zone D",
    date: "2026-08-02",
    time: "04:20 AM",
  },
  {
    id: "ALT-316",
    title: "Suspicious human footprint near check post",
    kind: "Human",
    species: "Human Footprint",
    priority: "High",
    status: "Acknowledged",
    source: "Footprint Upload",
    location: "Fence Line 7, Zone C",
    date: "2026-07-31",
    time: "02:12 AM",
  },
];

export const mockMarkers: MapMarker[] = mockDetections.map((d) => ({
  source: "Footprint Upload" as const,
  officerName: "Ranger Ravi",
  id: `MRK-${d.id}`,
  species: d.species,
  zone: d.zone,
  location: d.location,
  coordinates: d.coordinates,
  date: d.date,
  time: d.time,
}));

export const weeklyTrend = [
  { day: "Mon", animals: 6, human: 1 },
  { day: "Tue", animals: 9, human: 2 },
  { day: "Wed", animals: 5, human: 0 },
  { day: "Thu", animals: 11, human: 3 },
  { day: "Fri", animals: 8, human: 1 },
  { day: "Sat", animals: 13, human: 2 },
  { day: "Sun", animals: 10, human: 4 },
];
